### ISSUE TITLE
How should we use this class?

### ISSUE THREAD

**Issue by marcofranssen** [flugger/laravel-repository#1]
I tried following

```php
<?php

use Bluekiwi\User;

class UserRepository extends EloquentRepository implements UserRepositoryInterface
{
    public function __construct()
    {
        $this->model = User;
    }
}
```

However I'm not sure how to set the model...

Could you maybe add an examle to your readme.md

**Comment by flugger** [comment]
Hey Marco! My apologises. Still haven't gotten the time to write a short description on how the package works. The idea is to inject the model when you bind the repository to the service container. You can either create a RepositoryServiceProvider or add it directly to ApplicationServiceProvider:

```php
$this->app->bind( 'Bluekiwi/User/UserRepositoryInterface', function( $app ){
    return new /Bluekiwi/User/UserRepository( new /Bluekiwi/User );
} );
```

Let me know if you encounter other problems using it and I'll write up a short summary on how to use it in readme.md shortly. Thanks.
